//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolbox.Resources.ErrMessages", typeof(ErrMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error automatically re-adding disciplinaries to a rejoining user.
        /// </summary>
        public static string AutomaticDisciplinaryReapplication {
            get {
                return ResourceManager.GetString("AutomaticDisciplinaryReapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in bancleanse command.
        /// </summary>
        public static string BancleanseException {
            get {
                return ResourceManager.GetString("BancleanseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in ban command.
        /// </summary>
        public static string BanException {
            get {
                return ResourceManager.GetString("BanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in blacklist command.
        /// </summary>
        public static string BlacklistException {
            get {
                return ResourceManager.GetString("BlacklistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in checking for warn thresold.
        /// </summary>
        public static string CheckForWarnThresoldException {
            get {
                return ResourceManager.GetString("CheckForWarnThresoldException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in cleanse command.
        /// </summary>
        public static string CleanseException {
            get {
                return ResourceManager.GetString("CleanseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error parsing command.
        /// </summary>
        public static string CommandParsingException {
            get {
                return ResourceManager.GetString("CommandParsingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in configuration manager.
        /// </summary>
        public static string ConfigManagerException {
            get {
                return ResourceManager.GetString("ConfigManagerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in custom command.
        /// </summary>
        public static string CustomCommand {
            get {
                return ResourceManager.GetString("CustomCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error logging deleted message.
        /// </summary>
        public static string DeletedMessageException {
            get {
                return ResourceManager.GetString("DeletedMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in disciplinaries command.
        /// </summary>
        public static string DisciplinariesException {
            get {
                return ResourceManager.GetString("DisciplinariesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in discord context.
        /// </summary>
        public static string DiscordContextException {
            get {
                return ResourceManager.GetString("DiscordContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error logging edited message.
        /// </summary>
        public static string EditedMessageException {
            get {
                return ResourceManager.GetString("EditedMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in exile command.
        /// </summary>
        public static string ExileException {
            get {
                return ResourceManager.GetString("ExileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IO error.
        /// </summary>
        public static string FileIOException {
            get {
                return ResourceManager.GetString("FileIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in filter command.
        /// </summary>
        public static string FilterException {
            get {
                return ResourceManager.GetString("FilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in creating the gate message.
        /// </summary>
        public static string GateMessageCreationException {
            get {
                return ResourceManager.GetString("GateMessageCreationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in kick command.
        /// </summary>
        public static string KickException {
            get {
                return ResourceManager.GetString("KickException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in limit command.
        /// </summary>
        public static string LimitException {
            get {
                return ResourceManager.GetString("LimitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in logging moderation action.
        /// </summary>
        public static string ModerationActionException {
            get {
                return ResourceManager.GetString("ModerationActionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in mute command.
        /// </summary>
        public static string MuteException {
            get {
                return ResourceManager.GetString("MuteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not find config file.
        /// </summary>
        public static string NoConfigException {
            get {
                return ResourceManager.GetString("NoConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in overseer.
        /// </summary>
        public static string OverseerException {
            get {
                return ResourceManager.GetString("OverseerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in pardon command.
        /// </summary>
        public static string PardonException {
            get {
                return ResourceManager.GetString("PardonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in raidprotect command.
        /// </summary>
        public static string RaidprotectException {
            get {
                return ResourceManager.GetString("RaidprotectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in removing role from user.
        /// </summary>
        public static string RemoveRoleException {
            get {
                return ResourceManager.GetString("RemoveRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in returnban comamnd.
        /// </summary>
        public static string ReturnbanException {
            get {
                return ResourceManager.GetString("ReturnbanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in say command.
        /// </summary>
        public static string SayException {
            get {
                return ResourceManager.GetString("SayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in searchban command.
        /// </summary>
        public static string SearchbanException {
            get {
                return ResourceManager.GetString("SearchbanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in seymour initialization.
        /// </summary>
        public static string SeymourInitializationException {
            get {
                return ResourceManager.GetString("SeymourInitializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in storage manager.
        /// </summary>
        public static string StorageException {
            get {
                return ResourceManager.GetString("StorageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in unban command.
        /// </summary>
        public static string UnbanException {
            get {
                return ResourceManager.GetString("UnbanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in unblacklist command.
        /// </summary>
        public static string UnblacklistException {
            get {
                return ResourceManager.GetString("UnblacklistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in unlimit command.
        /// </summary>
        public static string UnlimitException {
            get {
                return ResourceManager.GetString("UnlimitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in unmute command.
        /// </summary>
        public static string UnmuteException {
            get {
                return ResourceManager.GetString("UnmuteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in userinfo command.
        /// </summary>
        public static string UserinfoException {
            get {
                return ResourceManager.GetString("UserinfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in verifying user.
        /// </summary>
        public static string UserVerifyException {
            get {
                return ResourceManager.GetString("UserVerifyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in warning command.
        /// </summary>
        public static string WarnException {
            get {
                return ResourceManager.GetString("WarnException", resourceCulture);
            }
        }
    }
}
