//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolbox.Resources.ErrMessages", typeof(ErrMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing command.
        /// </summary>
        public static string CommandParsingException {
            get {
                return ResourceManager.GetString("CommandParsingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in configuration manager.
        /// </summary>
        public static string ConfigManagerException {
            get {
                return ResourceManager.GetString("ConfigManagerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in discord context.
        /// </summary>
        public static string DiscordContextException {
            get {
                return ResourceManager.GetString("DiscordContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO error.
        /// </summary>
        public static string FileIOException {
            get {
                return ResourceManager.GetString("FileIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in filter command.
        /// </summary>
        public static string FilterException {
            get {
                return ResourceManager.GetString("FilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in information command.
        /// </summary>
        public static string InfoCommandException {
            get {
                return ResourceManager.GetString("InfoCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find config file.
        /// </summary>
        public static string NoConfigException {
            get {
                return ResourceManager.GetString("NoConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in seymour initialization.
        /// </summary>
        public static string SeymourInitializationException {
            get {
                return ResourceManager.GetString("SeymourInitializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in storage manager.
        /// </summary>
        public static string StorageException {
            get {
                return ResourceManager.GetString("StorageException", resourceCulture);
            }
        }
    }
}
