//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolbox.Resources.ErrMessages", typeof(ErrMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error automatically re-adding disciplinaries to a rejoining user.
        /// </summary>
        public static string AutomaticDisciplinaryReapplication {
            get {
                return ResourceManager.GetString("AutomaticDisciplinaryReapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in bancleanse command.
        /// </summary>
        public static string BancleanseException {
            get {
                return ResourceManager.GetString("BancleanseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in ban command.
        /// </summary>
        public static string BanException {
            get {
                return ResourceManager.GetString("BanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in blacklist command.
        /// </summary>
        public static string BlacklistException {
            get {
                return ResourceManager.GetString("BlacklistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in cleanse command.
        /// </summary>
        public static string CleanseException {
            get {
                return ResourceManager.GetString("CleanseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing command.
        /// </summary>
        public static string CommandParsingException {
            get {
                return ResourceManager.GetString("CommandParsingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in configuration manager.
        /// </summary>
        public static string ConfigManagerException {
            get {
                return ResourceManager.GetString("ConfigManagerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in custom command.
        /// </summary>
        public static string CustomCommand {
            get {
                return ResourceManager.GetString("CustomCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging deleted message.
        /// </summary>
        public static string DeletedMessageException {
            get {
                return ResourceManager.GetString("DeletedMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in disciplinaries command.
        /// </summary>
        public static string DisciplinariesException {
            get {
                return ResourceManager.GetString("DisciplinariesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in discord context.
        /// </summary>
        public static string DiscordContextException {
            get {
                return ResourceManager.GetString("DiscordContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging edited message.
        /// </summary>
        public static string EditedMessageException {
            get {
                return ResourceManager.GetString("EditedMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in exile command.
        /// </summary>
        public static string ExileException {
            get {
                return ResourceManager.GetString("ExileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO error.
        /// </summary>
        public static string FileIOException {
            get {
                return ResourceManager.GetString("FileIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in filter command.
        /// </summary>
        public static string FilterException {
            get {
                return ResourceManager.GetString("FilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in kick command.
        /// </summary>
        public static string KickException {
            get {
                return ResourceManager.GetString("KickException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in limit command.
        /// </summary>
        public static string LimitException {
            get {
                return ResourceManager.GetString("LimitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in mute command.
        /// </summary>
        public static string MuteException {
            get {
                return ResourceManager.GetString("MuteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find config file.
        /// </summary>
        public static string NoConfigException {
            get {
                return ResourceManager.GetString("NoConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in overseer.
        /// </summary>
        public static string OverseerException {
            get {
                return ResourceManager.GetString("OverseerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in pardon command.
        /// </summary>
        public static string PardonException {
            get {
                return ResourceManager.GetString("PardonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in raidprotect command.
        /// </summary>
        public static string RaidprotectException {
            get {
                return ResourceManager.GetString("RaidprotectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in returnban comamnd.
        /// </summary>
        public static string ReturnbanException {
            get {
                return ResourceManager.GetString("ReturnbanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in say command.
        /// </summary>
        public static string SayException {
            get {
                return ResourceManager.GetString("SayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in searchban command.
        /// </summary>
        public static string SearchbanException {
            get {
                return ResourceManager.GetString("SearchbanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in seymour initialization.
        /// </summary>
        public static string SeymourInitializationException {
            get {
                return ResourceManager.GetString("SeymourInitializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in storage manager.
        /// </summary>
        public static string StorageException {
            get {
                return ResourceManager.GetString("StorageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in unban command.
        /// </summary>
        public static string UnbanException {
            get {
                return ResourceManager.GetString("UnbanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in unblacklist command.
        /// </summary>
        public static string UnblacklistException {
            get {
                return ResourceManager.GetString("UnblacklistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in unlimit command.
        /// </summary>
        public static string UnlimitException {
            get {
                return ResourceManager.GetString("UnlimitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in unmute command.
        /// </summary>
        public static string UnmuteException {
            get {
                return ResourceManager.GetString("UnmuteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in userinfo command.
        /// </summary>
        public static string UserinfoException {
            get {
                return ResourceManager.GetString("UserinfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in warning command.
        /// </summary>
        public static string WarnException {
            get {
                return ResourceManager.GetString("WarnException", resourceCulture);
            }
        }
    }
}
